config/routes.rb
Rails.application.routes.draw do

  #get '/' => 'homes#top', as: 'root'
  root to: 'homes#top'
  
  get 'homes/top'
  get 'homes/new'
  get 'homes/index'
  get 'homes/show'
  get 'homes/edit'

  get 'books/new'
  get 'books/edit'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
   @book = Book.new
   @books = Book.all
  end

 def create
    @book = Book.new(book_params)
    if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)

    else
    @books = Book.all
    render :index
    end
 end


  def index
   @books = Book.all.order(id: :asc)
   @book = Book.new
   @books = Book.all
  end

  def show
     @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def back
     @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
    else
      render :edit

    end
  end

  def destroy

    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'

  end

 private
 def book_params
   params.require(:book).permit(:title, :body)
 end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def new
  end

  def index
  end

  def show
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>


<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%=message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

  <h4> Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>


  <div class="text-submit"><%= f.submit 'Update Book' %>
   <%= link_to "Show", book_path(@book.id) %>
   <%= link_to "Back", books_path %>
  </div>






<% end %>

app/views/books/index.html.erb
<h1>Books</h1>


<table>
    <thead>
        <tr>
            <th> Title</th>

            <th>Body</th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
            <tr>
                <td><%= book.title %></td>
                <td><%= book.body %></td>
                <td><%= link_to "Show", book_path(book) %></td>
                <td><%= link_to "Edit", edit_book_path(book) %></td>
                <td><%= link_to "Destroy", destroy_book_path(book), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
            </tr>
        <% end %>
    </tbody>
</table>



<h2>New Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%=message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book do |f| %>
  <div class="text-field">
    <div>Title</div>
    <%= f.text_field :title %>
  </div>
  <div class="text-area">
    <div>body</div>
    <%= f.text_area :body %>
    </div>

  <div class="text-submit"><%= f.submit 'Create Book' %></div>
<% end %>

app/views/books/new.html.erb
<h2>New Book</h2>

<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <h4> Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
  
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<% @post.errors.full_messages.each do |message| %>
 <div class="form-error">
  <%= message %>
 </div>
<% end %>
<textarea name="content"><%= @post.content %></textarea>
<input type="submit" value="投稿">

<% end %>

app/views/books/show.html.erb
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

<h4> Title</h4>
<p><%= @book.title %></p>

<h4>Body</h4>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/homes/edit.html.erb
<h1>Homes#edit</h1>
<p>Find me in app/views/homes/edit.html.erb</p>

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/homes/new.html.erb
<h1>Homes#new</h1>
<p>Find me in app/views/homes/new.html.erb</p>

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/homes/top.html.erb
<DOCTYPE html>
<html>

  <head>

    <title>WebcampBackendNew</title>


  </head>

  <body>
    <h1>ようこそBookersへ</h1>

    <p>Bookersでは、様々な書籍に関するあなたの意見や</p>
    <P>印象を共有し交換することができます</P>

    <P>
     <%= link_to 'start', books_path %>
    </P>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav>
      <ul class="nav-book">
        <li class="nav-book-item">

        </li>
        <li class="nav-book-item">
        </li>
        <li class="nav-book-item">
        </li>
      </ul>
    </nav>
    <main>
    <%= yield %>

    </main>
  </body>


</html>